Remove unused imports in Python code
Uninett/argus-htmx-frontend pull request #194
Opened 2024-10-22 12:29 UTC by johannaengland

To add F4 rules to ruff. 

Tagging as discussion to invite discussion if/which of these rules we want.

2024-10-24 06:28 UTC, lunkwill42 reviewed
I think this is a worthwhile linter rule.  Unused imports tend to clutter the codebase as it grows unless we have something to remind us to prune them.  @hmpf ?

2024-10-28 12:05 UTC, hmpf requested changes
This renders a dependency redundant, see comment.

2024-10-28 12:05 UTC, hmpf commented on src/argus_htmx/tests.py
> +from django.test import TestCase  # noqa: F401 - unused-import
Better to remove the file, it's autogenerated.

2024-10-28 12:05 UTC, hmpf commented on src/argus_htmx/models.py
> +from django.db import models  # noqa: F401 - unused-import
This file will be used by the userprefs-branch and should stay even if it was autogenerated.

2024-10-28 12:05 UTC, hmpf commented on src/argus_htmx/themes/views.py
> -import importlib_resources
This has a dependency that can be removed, see "pyproject.toml".

2024-10-28 12:13 UTC, hmpf approved these changes

2024-10-28 12:28 UTC, merged